# Generated by Django 4.0.5 on 2022-07-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerscategory',
            name='image',
            field=models.ImageField(null=True, upload_to='partners/images', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='partnerscategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Текст для ссылки (введите название категории на английском)'),
        ),
    ]
