# Generated by Django 4.0.5 on 2022-07-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partnerscategory_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriprion', models.TextField(null=True, verbose_name='Описание категории')),
                ('image', models.ImageField(null=True, upload_to='catalog/images', verbose_name='Изображение товара')),
                ('title', models.CharField(max_length=250, verbose_name='Имя товара')),
                ('file', models.FileField(upload_to='', verbose_name='Файл для партнеров')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partnerscategory', verbose_name='Категория')),
            ],
        ),
        migrations.DeleteModel(
            name='PartnersProducts',
        ),
    ]
