# Generated by Django 4.0.5 on 2022-07-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partnersproduct_delete_partnersproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersproduct',
            name='descriprion',
        ),
        migrations.AddField(
            model_name='partnerscategory',
            name='descriprion',
            field=models.TextField(null=True, verbose_name='Описание категории'),
        ),
    ]
