# Generated by Django 4.0.5 on 2022-07-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210824_0808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
