# Generated by Django 3.0 on 2021-08-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210805_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='add_in_home',
            field=models.BooleanField(null=True, verbose_name='Добавить категорию на главную страницу'),
        ),
    ]
