# Generated by Django 3.0 on 2021-08-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_add_in_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_of_category',
            field=models.CharField(max_length=250, null=True, verbose_name='Продублируйте имя категории в точности до символа'),
        ),
        migrations.AlterField(
            model_name='category',
            name='add_in_home',
            field=models.BooleanField(null=True, verbose_name='Добавить эту категорию на главную страницу?'),
        ),
    ]
