# Generated by Django 3.0 on 2021-08-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210809_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_of_category',
        ),
    ]
