# Generated by Django 3.0 on 2021-08-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_name_of_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='add_in_partners',
            field=models.BooleanField(null=True, verbose_name='Добавить эту категорию на cтраницу для пратнеров?'),
        ),
    ]
